#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v19
# autospec commit: f35655a
#
# Source0 file verified with key 0x08302DB6A2670428 (tim.ruehsen@gmx.de)
#
Name     : libpsl
Version  : 0.21.5
Release  : 25
URL      : https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz
Source0  : https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz
Source1  : https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz.sig
Source2  : 08302DB6A2670428.pkey
Summary  : Public Suffix List C library.
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: libpsl-bin = %{version}-%{release}
Requires: libpsl-lib = %{version}-%{release}
Requires: libpsl-license = %{version}-%{release}
Requires: libpsl-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : file
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(32icu-uc)
BuildRequires : pkgconfig(32libidn)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libidn)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description


%package bin
Summary: bin components for the libpsl package.
Group: Binaries
Requires: libpsl-license = %{version}-%{release}

%description bin
bin components for the libpsl package.


%package dev
Summary: dev components for the libpsl package.
Group: Development
Requires: libpsl-lib = %{version}-%{release}
Requires: libpsl-bin = %{version}-%{release}
Provides: libpsl-devel = %{version}-%{release}
Requires: libpsl = %{version}-%{release}

%description dev
dev components for the libpsl package.


%package dev32
Summary: dev32 components for the libpsl package.
Group: Default
Requires: libpsl-lib32 = %{version}-%{release}
Requires: libpsl-bin = %{version}-%{release}
Requires: libpsl-dev = %{version}-%{release}

%description dev32
dev32 components for the libpsl package.


%package lib
Summary: lib components for the libpsl package.
Group: Libraries
Requires: libpsl-license = %{version}-%{release}

%description lib
lib components for the libpsl package.


%package lib32
Summary: lib32 components for the libpsl package.
Group: Default
Requires: libpsl-license = %{version}-%{release}

%description lib32
lib32 components for the libpsl package.


%package license
Summary: license components for the libpsl package.
Group: Default

%description license
license components for the libpsl package.


%package man
Summary: man components for the libpsl package.
Group: Default

%description man
man components for the libpsl package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 08302DB6A2670428' gpg.status
%setup -q -n libpsl-0.21.5
cd %{_builddir}/libpsl-0.21.5
pushd ..
cp -a libpsl-0.21.5 build32
popd
pushd ..
cp -a libpsl-0.21.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726243555
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726243555
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libpsl
cp %{_builddir}/libpsl-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libpsl/0d5a75cad9426128ce1a87fd5ee7ecc46265e74a || :
cp %{_builddir}/libpsl-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libpsl/0d5a75cad9426128ce1a87fd5ee7ecc46265e74a || :
cp %{_builddir}/libpsl-%{version}/src/LICENSE.chromium %{buildroot}/usr/share/package-licenses/libpsl/73187e456b0901438d4982e4fcb4391a0e7dadef || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/psl
/usr/bin/psl
/usr/bin/psl-make-dafsa

%files dev
%defattr(-,root,root,-)
/usr/include/libpsl.h
/usr/lib64/libpsl.so
/usr/lib64/pkgconfig/libpsl.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libpsl.so
/usr/lib32/pkgconfig/32libpsl.pc
/usr/lib32/pkgconfig/libpsl.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpsl.so.5.3.5
/usr/lib64/libpsl.so.5
/usr/lib64/libpsl.so.5.3.5

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpsl.so.5
/usr/lib32/libpsl.so.5.3.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libpsl/0d5a75cad9426128ce1a87fd5ee7ecc46265e74a
/usr/share/package-licenses/libpsl/73187e456b0901438d4982e4fcb4391a0e7dadef

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/psl-make-dafsa.1
/usr/share/man/man1/psl.1
